-- auto-generated definition
create table poems
(
    id              bigint generated by default as identity
        primary key,
    created_at      timestamp with time zone default now(),
    title           text,
    content         text,
    email           varchar                  default auth.email(),
    illustrationurl text,
    hidden          boolean
);

create policy "Enable read access for all users si pas hidden" on poems
    as permissive
    for select
    using ((hidden <> true) OR (hidden IS NULL));

create policy "Enable update for users based on email" on poems
    as permissive
    for all
    using (auth.email() = (email)::text)
    with check (auth.email() = (email)::text);
    
alter table poems
    owner to supabase_admin;

grant select, update, usage on sequence poems_id_seq to postgres;

grant select, update, usage on sequence poems_id_seq to anon;

grant select, update, usage on sequence poems_id_seq to authenticated;

grant select, update, usage on sequence poems_id_seq to service_role;

grant delete, insert, references, select, trigger, truncate, update on poems to postgres;

grant delete, insert, references, select, trigger, truncate, update on poems to anon;

grant delete, insert, references, select, trigger, truncate, update on poems to authenticated;

grant delete, insert, references, select, trigger, truncate, update on poems to service_role;


